version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
        - "${APP_PORT:-8000}:80"
    volumes:
      - .:/src
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: "mysql:5"
    ports:
      - "33070:3306"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
