<?php

namespace App\Listeners;

use App\Events\UserRegistered;

class NotifyAboutRegistration
{
    public function handle(UserRegistered $event)
    {
        if ($event->passwordIsAutoGenerated) {
//            $event->user->notify();
        }
    }
}
