openapi: 3.0.2
info:
  title: Laravel test API
  version: '1.0'
servers:
  - url: /
tags:
  - name: auth
    description: Аутентификация
paths:
  /api/v1/auth/register:
    $ref: 'paths/register.yaml'
  /api/v1/auth/login:
    $ref: 'paths/login.yaml'
  /api/v1/auth/logout:
    $ref: 'paths/logout.yaml'
  /api/v1/auth/refresh:
    $ref: 'paths/refresh.yaml'
  /redirect/{driver}:
    $ref: 'paths/redirect-driver.yaml'
  /callback/{driver}:
    $ref: 'paths/callback-driver.yaml'
